// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarouselPreview: typeof import('./components/business/CarouselPreview.vue')['default']
    DrawerExport: typeof import('./components/classify/DrawerExport/DrawerExport.vue')['default']
    PreviewFile: typeof import('./components/classify/PreviewFile/PreviewFile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePage: typeof import('./components/classify/TablePage/TablePage.vue')['default']
  }
}
