// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-ui/lib/aside')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElContainer: typeof import('element-ui/lib/container')['default']
    ElDatePicker: typeof import('element-ui/lib/date-picker')['default']
    ElDivider: typeof import('element-ui/lib/divider')['default']
    ElDrawer: typeof import('element-ui/lib/drawer')['default']
    ElEmpty: typeof import('element-ui/lib/empty')['default']
    ElFooter: typeof import('element-ui/lib/footer')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElHeader: typeof import('element-ui/lib/header')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMain: typeof import('element-ui/lib/main')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElPageHeader: typeof import('element-ui/lib/page-header')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElStep: typeof import('element-ui/lib/step')['default']
    ElSteps: typeof import('element-ui/lib/steps')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElUpload: typeof import('element-ui/lib/upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
